### ISSUE TITLE
Add panelsets/tabsets?

### ISSUE THREAD

**Issue by apreshill** [dspatterns/dspatterns#11]
This is super effective for plots + code. 

There is this:
https://materializecss.com/tabs.html

or:
https://github.com/joeattardi/svelte-tabs

or:
https://pkg.garrickadenbuie.com/xaringanExtra/#/panelset

See also:
https://github.com/rstudio/distill/issues/11#issuecomment-692142414

I built in the js + css to my Hugo theme here:
https://hugo-apero.netlify.app/blog/seedling/
PR: https://github.com/apreshill/apero/pull/63

**Comment by rich-iannone** [comment]
I think that this would be great for all of the plot + code combinations. Okay if I test out your implementation (in https://hugo-apero.netlify.app/blog/seedling)? Less vertical space and scrolling for the reader would be nice.

One drawback (and it might be fine) is the figure numbering for ggplots. I kind of like the idea of *not* treating them as figures in the bookdown (but that's okay and probably necessary in the print edition).
